DROP TABLE IF EXISTS book_entity;

CREATE TABLE book_entity (
    isbn VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    publisher VARCHAR(255),
    date_published DATE,
    pages INT,
    language ENUM('ENGLISH', 'GERMAN', 'CHINESE', 'CROATIAN', 'FRENCH', 'ITALIAN', 'NORWEGIAN', 'PERSIAN', 'RUSSIAN', 'SANSKRIT', 'SPANISH', 'SWEDISH', 'TURKISH', 'CZECH'),
    genre ENUM('FICTION', 'NONFICTION', 'MYSTERY', 'THRILLER', 'HORROR', 'SCIENCE_FICTION', 'FANTASY', 'ROMANCE', 'WESTERN', 'DYSTOPIAN', 'CONTEMPORARY', 'CRIME', 'ADVENTURE', 'HISTORY', 'SELF_HELP', 'HEALTH', 'TRAVEL', 'CHILDREN', 'RELIGION', 'SCIENCE', 'HUMOR', 'COOKBOOKS', 'BIOGRAPHY', 'AUTOBIOGRAPHY', 'YOUNG_ADULT', 'PARANORMAL', 'ART', 'PSYCHOLOGY', 'GRAPHIC_NOVEL', 'POETRY'),
    PRIMARY KEY (isbn)
);
